#write a program to store seven fruits in a list entered by a user
fruits = []
f1 = input("enter a fruit")
fruits.append(f1)
f2 = input("enter a fruit")
fruits.append(f2)
f3 = input("enter a fruit")
fruits.append(f3)
f4= input("enter a fruit")
fruits.append(f4)
f5 = input("enter a fruit")
fruits.append(f5)
f6 = input("enter a fruit")
fruits.append(f6)
print(fruits)