s = {}
f1 = input("enter the key")
d1 = input("enter the value")
s.update({f1:d1})
f1 = input("enter the key")
d1 = input("enter the value")
s.update({f1:d1})
f1 = input("enter the key")
d1 = input("enter the value")
s.update({f1:d1})
f1 = input("enter the key")
d1 = input("enter the value")
s.update({f1:d1})
print(s)